### PR TITLE
implicit version install of netcdf4 to avoid netcdftime issue

### PR DESCRIPTION
**Pull request by anguss00**
@lwgordonimos thoughts?

### CODE REVIEW

**Comment by mhidas** [comment]
Will https://github.com/aodn/cc-plugin-imos/pull/12, combined with the chain of dependencies (aodndata > aodncore > cc-plugin-imos) ensure that the right version of netCDF4 will be used everywhere?
(That is, once we build and push the updated cc-plugin-imos to the prod environment. I've already built it on Jenkins.)

**Comment by anguss00** [comment]
Probably yes, this will then be an unnecessary step

**Comment by anguss00** [comment]
The magic of module dependency management is a black art to me ;-)

**Comment by mhidas** [comment]
Passed!
@lbesnard All your other PRs should also pass now, if this was the only thing wrong with them.

**Pull request closed without merging**
