### PR TITLE
Update unittests for compliance-checker upgrade

### PR DESCRIPTION
**Pull request by mhidas**
Since the new version of the compliance-checker includes checks for CF-1.7 and CF-1.8, all pipelines now need to explicitly request the CF-1.6 check suite (otherwise it defaults to 1.8).

See https://github.com/aodn/PO-Backlog/issues/3135 for context

### CODE REVIEW

**Comment by bpasquer** [comment]
looks good to me

**Comment by mhidas** [comment]
Thanks @bpasquer - shame the unittests are failing because in GH Actions we end up with compliance-checker 5.0.2 and its [bugs](https://github.com/aodn/PO-Backlog/issues/3092#issuecomment-1324584772).

**Comment by mhidas** [comment]
@bpasquer @lbesnard FYI this should fix the unittests here: https://github.com/aodn/python-aodncore/pull/270 - just need to promote it on Jenkins...

**Comment by mhidas** [comment]
@bpasquer @lbesnard This is ready to merge now that the new version of aodncore (1.4.6) has been promoted to prod. Merging this will then allow unittests in other PRs to pass (might need to rebase them).

**Review by bpasquer — APPROVED** [review]

**Pull request merged**
