### PR TITLE
Unittests for ImosBgcDbHandler

### PR DESCRIPTION
**Pull request by mhidas**

### CODE REVIEW

**Comment by mhidas** [comment]
@ndhogan I just added a couple more assertions, but I think this is still good to merge.

However, I just realised the GitHub Actions tests have not been triggered for this PR. Any idea why?? (@aodn/devops ??)

**Comment by mhidas** [comment]
> However, I just realised the GitHub Actions tests have not been triggered for this PR. Any idea why?? (@aodn/devops ??)

Same for https://github.com/aodn/python-aodncore/pull/242

**Comment by ndhogan** [comment]
> @ndhogan I just added a couple more assertions, but I think this is still good to merge.
> 
> However, I just realised the GitHub Actions tests have not been triggered for this PR. Any idea why?? (@aodn/devops ??)

@mhidas - GAs are only configured to execute on push / PR into master (see - https://github.com/aodn/python-aodndata/blob/wsd/.github/workflows/test.yml)

**Comment by mhidas** [comment]
> GAs are only configured to execute on push / PR into master

Ah yeah, I missed that point - or rather that we are not yet merging into master here.

**Comment by mhidas** [comment]
@ndhogan When I run this against the updated aodncore (after https://github.com/aodn/python-aodncore/pull/242), my `test_good_csv` now fails because it doesn't have a schema file to validate against.
Any thoughts on the simplest way to patch the config to point to a local schema file?
(Or mock `TableSchemaCheckRunner` to mark the pipelinefile as valid without looking for the schema file?)

**Comment by mhidas** [comment]
This should be good to go now.

**Pull request merged**
