### PR TITLE
Updating mooring pipeline to ingest NTP profiling mooring files

### PR DESCRIPTION
**Pull request by leonardolaiolo**
@mhidas I believe the check fails are related to the issues that you are already fixing for mooring products? Here is the error I get in my local machine when I run the `test_mooringsProductsHandler.py`:
> FAILED [ 41%]
test_aodndata/moorings/test_mooringsProductsHandler.py:130 (TestMooringsProductsHandler.test_velocity_hourly)
self = <test_aodndata.moorings.test_mooringsProductsHandler.TestMooringsProductsHandler testMethod=test_velocity_hourly>

### CODE REVIEW

**Review by mhidas — APPROVED** [review]
:+1: Good work!

**Comment by mhidas** [comment]
> @mhidas I believe the check fails are related to the issues that you are already fixing for mooring products?

Yes, in fact it's a bug I introduced myself :smirk: - it has been fixed in the latest version of aodntools, so all good now!

**Comment by mhidas** [comment]
@leonardolaiolo FYI I was looking at Jenkins and accidentally clicked the `promote_prod` button on aodndata, so this change will be on prod tomorrow. We haven't been able to test it in RC, but I'm pretty confident it won't break anything in prod, so we'll just leave it.

**Comment by leonardolaiolo** [comment]
No worries Marty, thanks for the update. Tomorrow I'll double check and if everything is okay in prod and I can then get in touch with Pete and he can start uploading files.

**Pull request merged**
